### ISSUE TITLE
Automate Weekly Email Regarding Availability of Attorneys to Volunteer

### ISSUE THREAD

**Issue by BiblioT3chie** [usdigitalresponse/npi-lawyer-client-matching#23]
This solution needs to be investigated using the *Staff List* tab in the [Matching Spreadsheet](https://docs.google.com/spreadsheets/u/0/d/1F0olntJaDIs-7Z1etzr-FKNkEWX-DD_sz91HH1-6Bf8/) with the verbiage in the [First Email](https://docs.google.com/document/d/1mY---dj1gzcuxnI9YQAnb7RNIKIS3nTpWfZWv5uPNZ4/edit#heading=h.s3h4uyxxbih9).

**Comment by BiblioT3chie** [comment]
Triana is investigating a mail merge opportunity.

**Comment by chrisxkeith** [comment]
Might be able to

- Add a hidden sheet to the matching workbook.
- Add a time-based trigger to the sheet to add a row at a specific time/day.
- Add a Zap that watches that hidden sheet, and send an email when a row is added (or updated?)

**Comment by chrisxkeith** [comment]
https://developers.google.com/workspace/solutions/mail-merge

**Comment by chrisxkeith** [comment]
Text of email. Will need to HTML-ize it. Attorney emails go into cc, not bcc.

Hello,

You are receiving this email because you volunteered your time to support the Eviction Settlement Program, providing legal support on eviction cases in Shelby County. If you are available to take on a new case next week, April 26 - April 30, please let us know by filling out this form by the end of the day today, Thursday, April 22nd.


Background:

    This is a weekly reminder, asking you to submit your availability for the following week.
    Volunteers should expect each case to take approximately 5 hours a week, and last approximately two weeks.
    If you have availability, you may receive an email pairing you with a potential client. Confirming availability does not bind you to a case - you will have the opportunity to do a conflict check and confirm your availability before accepting a case. If you choose to accept a case, you will be given access to the necessary client details to proceed.

What you need to do:

    Eviction cases move quickly. The sooner you submit availability with this online form, the faster we can find a potential match.
    If you are not available this week, you do not have to fill out the form. We’ll email every week to check in on availability to take on new clients.
    Once you receive a case assignment, please review the details and confirm that you are able to take on the case.

Thank you for your valuable work and support in helping preserve our neighbors and communities in Shelby County.


Neighborhood Preservation Inc.

npimemphis.org

Facebook | Instagram | Twitter

Please note, esp@npimemphis.org is an automated messaging address, and responses directly to this email address will not be read. If you have questions about this email, would like to update your volunteer contact information, please reach out to Steve Barlow.

**Comment by chrisxkeith** [comment]
Source code : https://github.com/googleworkspace/solutions/tree/master/mail-merge

**Comment by chrisxkeith** [comment]
GMailApp sendEmail() documentation : https://developers.google.com/apps-script/reference/gmail/gmail-app#sendemailrecipient,-subject,-body

**Comment by chrisxkeith** [comment]
Got a proof-of-concept working.

Proposed functionality for v1:
- Automated email goes out Wednesday morning between 8am-9am, Memphis time zone. This allows attorneys 2 days to respond.
- Contents of the email are generic (e.g., 'by the end of the day Thursday', not 'by the end of day Thursday, April 22').
- Attorney emails are in bcc. Google Scripts has limit of 50 email addresses per email, so multiple emails might go out.
- After those emails are sent, a summary email is sent to steve@npimemphis.org (and anyone else who wants to be notified) with a subject line similar to: 'Emailed 97 attorneys asking for their availability'

Putting the specific dates into the emails will be handled when necessary. I will open another issue for that.

**Comment by chrisxkeith** [comment]
Enabled in production.
